services:
  - type: web
    name: relationship-garden
    env: node
    plan: free
    buildCommand: cd /opt/render/project && npm install && npm run build
    startCommand: cd /opt/render/project && npm run start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: / 