services:
  - type: web
    name: relationship-garden
    env: node
    plan: free
    buildCommand: pwd && ls -la && npm install && npx vite build -c vite.config.ts && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: / 